### ISSUE TITLE
exlusionary and generally useless note

### ISSUE THREAD

**Issue by ryanflorence** [magomimmo/modern-cljs#177]
> NOTE 1: I'm of the opinion that CLJS should be easier to set up not only to use, as server-side devs, but for smart client-side devs as well. Application logic is moving fast from server-side to client-side and all of us, as server-side devs, never had much love for that LISP dressed in C running in the browser and named JS. We now have the opportunity to see the best LISP ever running in the browser and we should try to bring client-side programmers with us. Otherwise, we risk seeing said LISP in C's clothing running on the server-side too.

As somebody who has pretty much only written JavaScript for browsers in my career I read this and feel like I'm in the side of the room while you talk to the "other smart server devs".

Us client-side devs are going to get into clojure via clojurescript, might want to reconsider your audience :)

**Comment by magomimmo** [comment]
Hi Rayn,
I beg your pardon if my note made to you that impression, which was not in my intention when I wrote it more than 2 years ago. At those time, to setup a CLJS project was a PITA, if compared with any other JS lib. Yes, I was talking to the server-dev side of the room, to ask them to make CLJS easier to be setup (which now is much easier) if they would like to include client-devs. Not because they are not smart, but because they are accustomed to much easier setup.  

That said, in the latest few months my team is working very hard on CLJS on nodeJS/microcontroller by using a lot the core.async lib, which is a kind of dream if compared with the callback hell generated by directly using JS. We have chosen CLJS instead of CLJ because the start-up time of the JVM on those microcontroller (e.g. raspberry pi) was unacceptable. We’re very happy with this setup.   

My best
mimmo
