### ISSUE TITLE
Tutorial 5: nrepl hangs when evaluating validate-form

### ISSUE THREAD

**Issue by mcortesi** [magomimmo/modern-cljs#211]
I'm folowing all tutorials step by step with no problems.

But in tutorial 5, after i change validate-form in login.cljs, i can't evaluate it in the repl.
What i do is

   $  lein trampoline cljsbuild repl-listen  
   Running ClojureScript REPL, listening on port 9000. 
   To quit, type: :cljs/quit
   ClojureScript:cljs.user> (in-ns 'modern-cljs.login)

   ClojureScript:modern-cljs.login> validate-form

and it hangs there, it never comes back. Probably it's a silly thing but since there is not error output, and I'm new to clojure i don't know how to proceed.

**Comment by talexand** [comment]
I'm having the same issue.

**Comment by fragamus** [comment]
Same here.

**Comment by Txellenne** [comment]
same :{

**Comment by magomimmo** [comment]
sorry to be late. I'm in the process to update the entire series, currently up to tutorial'05. aside from few annoying warnings caused by the latest cljs release (1.7.145) and domina non adhering to the latest cljs convention everything should work. 

you could eventually try the following:

cljs.user> (require '[modern-cljs.login :as login])
cljs.user> login/validate-form

cheers

**Comment by magopian** [comment]
Using the tip from @magomimmo the error is different, but it's still an error (the example pasted is for the shopping calculator, but it does exactly the same for the login):
```
cljs.user=> (require '[modern-cljs.shopping :as s])
nil
cljs.user=> (shopping/calculate)
TypeError: modern_cljs.shopping is undefined
```

This is really strange as the exact same technique worked perfectly for the end of tutorial 4. Could it be that the error/warning introduced by domina causes this issue?

**Comment by magomimmo** [comment]
Hi Mathieu,
I got the chance to test the tutorial-05.

I did the following to test the orginal code

$ git clone https://github.com/magomimmo/modern-cljs.git <https://github.com/magomimmo/modern-cljs.git>
$ cd modern-cljs
$ git checkout tutorial-05

then I run the ring server in a terminal

$ lein ring server-headless

In another window I compiled the CLJS code

$ cd /path/to/modern-cljs
$ lein cljsbuild once

Yuo’ll receive more warnings regarding domina. Until tutorial-07 they should not create problems

Finally I launched the real

$ lein trampoline cljsbuild repl-listen

again you’ll receive some warning on domina (and a parser error, which depends on the latest CLJS 1.7.145). do not care about them

Wait a while and then visit localhost:3000/login.html

If the repl hang, try to reload the login page. 

then I could follow the tutorial without problems. 

this type of bREPL connection is very weak. This is one of the reason why I’m writing a second edition, 

Take a look a this two draft tutorial that will substitute the original one:

https://github.com/magomimmo/modern-cljs/blob/second-edition/doc/tutorial-01.md <https://github.com/magomimmo/modern-cljs/blob/second-edition/doc/tutorial-01.md>
https://github.com/magomimmo/modern-cljs/blob/second-edition/doc/tutorial-02.md <https://github.com/magomimmo/modern-cljs/blob/second-edition/doc/tutorial-02.md>

do not use the git command in the preamble, because they are still to be checked out in the repo.

HIH

Mimmo

**Comment by magomimmo** [comment]
the first edition of the modern-cljs series is no more active/supported.
