### ISSUE TITLE
Reader Conditionals

### ISSUE THREAD

**Issue by xcthulhu** [magomimmo/modern-cljs#214]
Maybe this tutorial could be moved to Clojure 1.7.0 and have a chapter on reader conditionals?

http://dev.clojure.org/display/design/Reader+Conditionals

**Comment by magomimmo** [comment]
Absolutely right. I'm in the process of updating the whole series. I do not have a lot of spare time, but I'll do my best.

cheers
mimmo

**Comment by magomimmo** [comment]
Hi @xcthulhu, I'm currently working on the second edition of the series. I already ported (and fixed few bugs) the `valip` lib on the `1.7.0` reader conditionals. I also already re-wrote 11 tutorials in this second edition, which also uses `boot` building tool instead of leiningen/cljsbuild/cljx. 

I'm in the process of writing the tutorial about the reader conditionals which solved the features expression problem. 

As soon as the tutorial dedicated to this topic is ready I let you know.

**Comment by magomimmo** [comment]
the first edition of the modern-cljs series is no more active/supported.
