### ISSUE TITLE
Instructions for connecting Emacs to REPLs

### ISSUE THREAD

**Issue by learningcljs** [magomimmo/modern-cljs#340]
In [tutorial 2](https://github.com/learningcljs/modern-cljs/blob/master/doc/second-edition/tutorial-02.md) it says:

> If your editor supports nrepl you are going to use that information to connect to the now running nrepl server with an nrepl client

In [tutorial 15](https://github.com/magomimmo/modern-cljs/blob/master/doc/second-edition/tutorial-15.md) it says:

> NOTE 5: I use emacs+cider

How is Emacs connected to REPLs?  It would be nice to have a short set of instructions on this in modern-cljs/doc/supplemental-material/ which could be linked to when this topic comes up in the tutorial series as the instruction on enabling and disabling JS are.

**Comment by magomimmo** [comment]
We could eventually add few appendices on this kind of practical aspects regarding tooling. We could even add instructions on creating a docker environment, etc. That said I'm using emacs because I know it very well, but I won't penalize any other editor/IDE. In the future I would like to see atom editor to be fully integrated with clojure(script), this is because atom seems to have a good adoption by front-ender/nodejs devs. Perhaps at the moment the best and less hard thing to do it is to add few references to clojure for the brave free book and to cider docs as well.

**Comment by learningcljs** [comment]
I am submitting pull request #350 to close this issue. I have gone with the suggestion:
> Perhaps at the moment the best and less hard thing to do it is to add few references to clojure for the brave free book and to cider docs as well.

**Comment by learningcljs** [comment]
With pull request #350 merged I think this issue can be closed.
