### ISSUE TITLE
Tutorial 1: adzerk/boot-cljs "1.7.228-2" is not found in clojars

### ISSUE THREAD

**Issue by elliotec** [magomimmo/modern-cljs#431]
The dependency in the first tutorial can't be found and I'm unable to progress after trying different versions.

**Comment by kranki** [comment]
If you typo something, boot may not find the jar. Double check the spelling. The error messages aren't always the most helpful.

You can also clone the repo and go to Tutorial 2
`git clone https://github.com/magomimmo/modern-cljs.git`
`cd modern-cljs`
`git checkout se-tutorial-01`
to see if the problem persists.

Otherwise it would be helpful to post the contents of your build.boot, the full error message etc.

**Comment by elliotec** [comment]
Ok thanks for the reply. Looks like it probably was a typo, I redid it and it works. 👍
